<a href="https://colab.research.google.com/github/Devsah9051/Bangalore-House-Price-Prediction/blob/main/HOUSE_PRICE_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Bangalore House Price Prediction

In [ ]:
#important libraries :
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [ ]:
#extracting the file from dataset :
df=pd.read_csv("/content/Bangalore  house data.csv")

In [ ]:
#checking the head values of dataset:
df.head(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [ ]:
#checking the sample value here:
df.sample(5)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
1855,Super built-up Area,18-Dec,Lalbagh Road,4 BHK,NaN,3675,4.0,3.0,367.0
5719,Super built-up Area,Ready To Move,Whitefield,3 BHK,NaN,1862,3.0,2.0,125.0
151,Super built-up Area,Ready To Move,Kannamangala,2 BHK,VBownre,957,2.0,1.0,58.0
10033,Super built-up Area,Ready To Move,Whitefield,2 BHK,NaN,1190,2.0,3.0,59.0
2926,Super built-up Area,Ready To Move,Tindlu,3 BHK,Shmolti,1357,2.0,2.0,65.0

In [ ]:
#checking the information of dataset here:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [ ]:
#seeing the description of dataset :
df.describe()#all are in lakh:

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [ ]:
#also finding the the duplicated value
df.duplicated().sum()

np.int64(529)

In [ ]:
#droping the duplicated value fro the dataset :
df.drop_duplicates(inplace=True)

In [ ]:
#checking the value count in each columns:
for column in df.columns:
  print(df[column].value_counts())
  print("*"*100)

area_type
Super built-up  Area    8317
Built-up  Area          2398
Plot  Area              1989
Carpet  Area              87
Name: count, dtype: int64
****************************************************************************************************
availability
Ready To Move    10172
18-May             292
18-Dec             284
18-Apr             269
18-Aug             187
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
****************************************************************************************************
location
Whitefield                   523
Sarjapur  Road               379
Electronic City              287
Kanakpura Road               249
Thanisandra                  229
                            ...
Hanuman Nagar                  1
Chuchangatta Colony            1
Electronic City Phase 1,       1
Chikbasavanapura               1
Abshot Layout                  1
Name: count, Length: 1305, dtype: int64
****************************************************************************************************
size
2 BHK         4931
3 BHK         4120
4 Bedroom      824
4 BHK          574
3 Bedroom      535
1 BHK          521
2 Bedroom      314
5 Bedroom      291
6 Bedroom      191
1 Bedroom      104
8 Bedroom       84
7 Bedroom       82
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
****************************************************************************************************
society
GrrvaGr    68
PrarePa    63
Sryalan    56
Prtates    54
GMown E    52
           ..
Rencyes     1
DiaveEn     1
Suiumy      1
NCold G     1
JaghtDe     1
Name: count, Length: 2688, dtype: int64
****************************************************************************************************
total_sqft
1200       808
1100       210
1500       202
2400       196
600        178
          ...
1379         1
1648         1
2872         1
1331.95      1
6688         1
Name: count, Length: 2117, dtype: int64
****************************************************************************************************
bath
2.0     6546
3.0     3180
4.0     1198
1.0      762
5.0      520
6.0      271
7.0      102
8.0       64
9.0       42
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
****************************************************************************************************
balcony
2.0    4846
1.0    4700
3.0    1630
0.0    1010
Name: count, dtype: int64
****************************************************************************************************
price
75.00    300
65.00    296
55.00    265
60.00    263
45.00    231
        ...
61.11      1
46.56      1
42.54      1
47.35      1
69.76      1
Name: count, Length: 1994, dtype: int64
****************************************************************************************************

In [ ]:
#finding the nullvalues in the dataset :
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5328
total_sqft         0
bath              73
balcony          605
price              0
dtype: int64

In [ ]:
#droping the values which not make impact the value of house:
df.drop(columns=['area_type','availability','society'],inplace=True)

In [ ]:
#filling the values where value is null :
#first in location :
df['location'] = df["location"].fillna("Sarjapur  Road ")
#handel thenull value in size:
df['size'] = df['size'].fillna("2 BHK")
#handel now the bathroom :
df['bath'] = df['bath'].fillna(df['bath'].median())

In [ ]:
#handle the bhk problem :
df["bhk"]=df['size'].str.split().str.get(0).astype(int)

In [ ]:
#checking the range of total_sqft":
df["total_sqft"].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [ ]:
#handle the range of the total_sqft:
def convert_range(x):
  temp=x.split('-')
  if len(temp)==2:
    return (float(temp[0])+float(temp[1]))/2 #getting the mean here of values:
  try:
    return float(x)
  except:
    return None

df["total_sqft"]=df["total_sqft"].apply(convert_range)

# Price Per Square feet

In [ ]:
#making new columns here:
df["price_per_sqft"]=df['price']*100000/df['total_sqft']
df['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13314     6530.612245
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
Name: price_per_sqft, Length: 12791, dtype: float64

In [ ]:
df.head()
df['bath'].describe()#max=16
df[['bath','price']].corr()

           bath     price
bath   1.000000  0.451203
price  0.451203  1.000000

In [ ]:
#reduce the number of location :
df['location']=df['location'].apply(lambda x:x.strip())#remove the space from front and back:
location_count=df['location'].value_counts()
location_count

location
Whitefield            524
Sarjapur  Road        380
Electronic City       289
Kanakpura Road        249
Thanisandra           232
                     ...
Hsr layout sector3      1
Thyagraj Nagar          1
Banagirinagar           1
Medaralli               1
Chikkajala              1
Name: count, Length: 1294, dtype: int64

In [ ]:
location_count_lessthan10=location_count[location_count<=10]
location_count_lessthan10
df['location']=df['location'].apply(lambda x:'Others' if x in location_count_lessthan10 else x)

In [ ]:
df['location'].value_counts()

location
Others              2933
Whitefield           524
Sarjapur  Road       380
Electronic City      289
Kanakpura Road       249
                    ...
Banjara Layout        11
Tindlu                11
Doddakallasandra      11
Thyagaraja Nagar      11
HAL 2nd Stage         11
Name: count, Length: 234, dtype: int64

# Outlier handle :

In [ ]:
#handle the outlier in total_sqft;
(df['total_sqft']/df['bhk']).describe()

count    12745.000000
mean       576.331501
std        395.528011
min          0.250000
25%        473.333333
50%        552.500000
75%        626.666667
max      26136.000000
dtype: float64

In [ ]:
#now putting all the value which only have total_sqft>=300 are actual flat:
df=df[(df['total_sqft']/df['bhk'])>=300]
df.describe()

,total_sqft,bath,balcony,price,bhk,price_per_sqft
count,12011.000000,12011.000000,11499.000000,12011.000000,12011.000000,12011.000000
mean,1606.223870,2.571643,1.586225,113.252382,2.660644,6363.396694
std,1283.874933,1.090077,0.814359,154.815223,0.988055,4226.681217
min,300.000000,1.000000,0.000000,8.440000,1.000000,267.829813
25%,1117.000000,2.000000,1.000000,49.975000,2.000000,4250.000000
50%,1306.000000,2.000000,2.000000,70.000000,3.000000,5330.490405
75%,1715.000000,3.000000,2.000000,120.000000,3.000000,6967.569041
max,52272.000000,16.000000,3.000000,3600.000000,16.000000,176470.588235

In [ ]:
df.shape

(12011, 8)

In [ ]:
#here making the subdf for making the price_per_sqft into range of mean+std to mean-stdL:
def remove_outlier_sqft(df):
  df_output=pd.DataFrame()
  for key,subdf in df.groupby('location'):
    m=np.mean(subdf.price_per_sqft)
    st=np.std(subdf.price_per_sqft)
    gen_new_df=subdf[(subdf.price_per_sqft>=(m-st))&(subdf.price_per_sqft<=(m+st))]
    df_output=pd.concat([df_output,gen_new_df],ignore_index=True)
  return df_output


df=remove_outlier_sqft(df)
df.describe()

,total_sqft,bath,balcony,price,bhk,price_per_sqft
count,9898.000000,9898.000000,9529.000000,9898.000000,9898.000000,9898.000000
mean,1519.211343,2.484946,1.591563,92.718584,2.583249,5707.005643
std,896.553698,0.993780,0.802125,87.882270,0.908010,2285.505781
min,300.000000,1.000000,0.000000,10.000000,1.000000,1250.000000
25%,1108.000000,2.000000,1.000000,49.735000,2.000000,4280.955021
50%,1297.500000,2.000000,2.000000,68.000000,2.000000,5208.333333
75%,1662.000000,3.000000,2.000000,100.000000,3.000000,6491.745419
max,30400.000000,16.000000,3.000000,2200.000000,16.000000,24509.803922

In [ ]:
#handleing the outlier in the bhk:
def bhk_outlier_remove(df):
  exclude_indices=np.array([])
  for location,location_df in df.groupby("location"):#set of groupby value of same location :
    bhk_stats={}#used to store the mean ,std,count of house in same set of groupby location :
    for bhk,bhk_df in location_df.groupby("bhk"):
      bhk_stats[bhk]={
          "mean":np.mean(bhk_df.price_per_sqft),
          "std":np.std(bhk_df.price_per_sqft),
          "count":bhk_df.shape[0]
          }
    for bhk,bhk_df in location_df.groupby("bhk"):#compairing the bhk size in neighbourhood:
      stats=bhk_stats.get(bhk-1)
      if stats and stats['count']>5:
        exclude_indices=np.append(exclude_indices,bhk_df[bhk_df.price_per_sqft<(stats['mean'])].index.values)
  return df.drop(exclude_indices,axis='index')


  df=bhk_outlier_remove(df)

In [ ]:
  df.shape

(9898, 8)

In [ ]:
df.sample(5)

,location,size,total_sqft,bath,balcony,price,bhk,price_per_sqft
2303,Gottigere,2 BHK,950.0,2.0,1.0,38.000,2,4000.000000
3940,Kanakpura Road,2 BHK,700.0,2.0,1.0,35.070,2,5010.000000
3205,Hoskote,2 BHK,1003.5,2.0,0.0,28.095,2,2799.701046
7665,Raja Rajeshwari Nagar,1 BHK,648.0,1.0,1.0,31.750,1,4899.691358
9578,Whitefield,3 BHK,2321.0,4.0,1.0,157.000,3,6764.325722

In [ ]:
#droping the price_per_sqft because it give extra and make perdiction easy and balcony beacuse it have less correation with the price here:
df.drop(columns=['balcony','price_per_sqft','size'],inplace=True, errors='ignore')

In [ ]:
df.sample(5)

            location  total_sqft  bath  price  bhk
9457      Whitefield      1570.0   3.0   88.0    3
8222  Sarjapur  Road      3044.0   3.0  183.0    3
9130     Vittasandra      1404.0   2.0   70.0    2
1163    Billekahalli      2968.0   3.0  225.0    3
3730  Kaikondrahalli      1250.0   2.0   78.0    2

# Split the data into X,y:

In [ ]:
X=df.drop(columns=['price'])
y=df['price']

In [ ]:
#here importing all important libraries of sklearn :
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [ ]:
#splitting here:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=10)

In [ ]:
print(X_train.shape,X_test.shape,X.shape,y.shape)

(7918, 4) (1980, 4) (9898, 4) (9898,)

In [ ]:
#here making the columns_transformer :
columns_trans=make_column_transformer((OneHotEncoder(sparse_output=False),['location']),
                                       ( StandardScaler(),['total_sqft']),
                                      remainder='passthrough')

In [ ]:
#selecting multiple model in one place :
model={
    "Linear Regression":LinearRegression(),
    "Lasso Regression ":Lasso(),
    "Ridge Rgression ":Ridge()
}
results={}

for name,model_instance in model.items():
  pipe=make_pipeline(columns_trans,model_instance)
  pipe.fit(X_train,y_train)
  y_pred=pipe.predict(X_test)
  score=r2_score(y_test,y_pred)
  results[name] = score
  print(f"✅ {name} trained. R2 Score: {score:.4f}")

✅ Linear Regression trained. R2 Score: 0.7701
✅ Lasso Regression  trained. R2 Score: 0.6575
✅ Ridge Rgression  trained. R2 Score: 0.7747

In [ ]:
#viewingh the winner here:
summary_df=pd.DataFrame(list(results.items()),columns=['Model','R2_Score'])
summary_df=summary_df.sort_values(by='R2_Score',ascending=False)
print(summary_df.to_string(index=False))

            Model  R2_Score
 Ridge Rgression   0.774717
Linear Regression  0.770089
Lasso Regression   0.657500

# Hyperparameter tunning to increase the R2_score

In [ ]:
#perfoming the hyperparameter tunning in Ridge Regression :
from sklearn.model_selection import GridSearchCV
#defining the parameter of ridge regression:
ridge_params={'ridge__alpha':[0.1,1.0,10.0,100.0]}
#pipeline of this :
pipeline_ridge=make_pipeline(columns_trans,Ridge())
#Perform gride_search cv:
gride_ridge=GridSearchCV(pipeline_ridge,ridge_params,cv=5,scoring='r2',n_jobs=-1,verbose=1)
#fit the pipeline with gridesearchcv:
gride_ridge.fit(X_train, y_train)

#selecting the best model and r2_score:
best_ridge=gride_ridge.best_estimator_
best_ridge_r2=gride_ridge.best_score_

#showing in screen:
results['Ridge Rgression (Tunned)']=best_ridge_r2

Fitting 5 folds for each of 4 candidates, totalling 20 fits

In [ ]:
#viewing the score:
summary_df_final_ridge=pd.DataFrame(list(results.items()),columns=['Model','R2_Score'])
summary_df_final_ridge=summary_df_final_ridge.sort_values(by="R2_Score",ascending=False)
print(summary_df_final_ridge.to_string(index=False))

                   Model  R2_Score
Ridge Rgression (Tunned)  0.812880
        Ridge Rgression   0.774717
       Linear Regression  0.770089
       Lasso Regression   0.657500

In [ ]:
#hyperparamter tunning with lasso regression :
#lasso params:
lasso_params={'lasso__alpha':[0.001,0.01,0.1,1.0,10.0]}
#pipeline for lasso :
pipeline_lasso=make_pipeline(columns_trans,Lasso())
#gridsearchcv for lasso :
gride_lasso=GridSearchCV(pipeline_lasso,lasso_params,cv=5,scoring ='r2',n_jobs=-1,verbose=1)
#fitting the model:
gride_lasso.fit(X_train,y_train)
#selecting the best model and r2_score:
best_lasso=gride_lasso.best_estimator_
best_lasso_r2=gride_lasso.best_score_

#shopwing the results:
results['Lasso Regression (Tunned)']=best_lasso_r2


#showing the results :
summary_df_final_lasso=pd.DataFrame(list(results.items()),columns=['Model','R2_Score'])
summary_df_final_lasso=summary_df_final_lasso.sort_values(by="R2_Score",ascending=False)
print(summary_df_final_lasso.to_string(index=False))

Fitting 5 folds for each of 5 candidates, totalling 25 fits
                    Model  R2_Score
 Ridge Rgression (Tunned)  0.812880
Lasso Regression (Tunned)  0.812803
         Ridge Rgression   0.774717
        Linear Regression  0.770089
        Lasso Regression   0.657500

In [ ]:
import pickle
pickle.dump(pipe,open('RidgeModel.pkl','wb'))

In [ ]:
#testing the output of my prediction :

# Select a random index from the test set
import random
random_index = random.randint(125, len(X_test) - 1)

# Get the input data for prediction from X_test
input_data = X_test.iloc[[random_index]]

# Get the actual price from y_test for comparison
original_price = y_test.iloc[random_index]

print(f"Details of the selected house from X_test:\n{input_data.to_string(index=False)}")

# Make a prediction using the best Ridge Regression model
predicted_price = best_ridge.predict(input_data)

print(f"\nThe predicted price for this house is: ₹{predicted_price[0]:.2f} Lakhs")
print(f"The actual price (from y_test) for this house was: ₹{original_price:.2f} Lakhs")

Details of the selected house from X_test:
location  total_sqft  bath  bhk
  Gunjur      1140.0   2.0    2

The predicted price for this house is: ₹42.53 Lakhs
The actual price (from y_test) for this house was: ₹49.11 Lakhs